[2024-12-16T16:42:47.803+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-16T16:42:47.818+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK_DEPN_2.Run_bash_to_python_file manual__2024-12-16T16:19:01.058214+00:00 [queued]>
[2024-12-16T16:42:47.827+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PRCS_TEST_FRAMEWORK_DEPN_2.Run_bash_to_python_file manual__2024-12-16T16:19:01.058214+00:00 [queued]>
[2024-12-16T16:42:47.828+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 6
[2024-12-16T16:42:47.840+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): Run_bash_to_python_file> on 2024-12-16 16:19:01.058214+00:00
[2024-12-16T16:42:47.846+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=170) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-16T16:42:47.849+0000] {standard_task_runner.py:72} INFO - Started process 201 to run task
[2024-12-16T16:42:47.847+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'PRCS_TEST_FRAMEWORK_DEPN_2', 'Run_bash_to_python_file', 'manual__2024-12-16T16:19:01.058214+00:00', '--job-id', '1960', '--raw', '--subdir', 'DAGS_FOLDER/script/PRCS_TEST_FRAMEWORK_DEPN_2.py', '--cfg-path', '/tmp/tmp4f3c9mfy']
[2024-12-16T16:42:47.852+0000] {standard_task_runner.py:105} INFO - Job 1960: Subtask Run_bash_to_python_file
[2024-12-16T16:42:47.909+0000] {task_command.py:467} INFO - Running <TaskInstance: PRCS_TEST_FRAMEWORK_DEPN_2.Run_bash_to_python_file manual__2024-12-16T16:19:01.058214+00:00 [running]> on host 3b6d26b512f1
[2024-12-16T16:42:48.088+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='test-framework' AIRFLOW_CTX_DAG_ID='PRCS_TEST_FRAMEWORK_DEPN_2' AIRFLOW_CTX_TASK_ID='Run_bash_to_python_file' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T16:19:01.058214+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T16:19:01.058214+00:00'
[2024-12-16T16:42:48.091+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-16T16:42:48.109+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-16T16:42:48.134+0000] {process_utils.py:132} INFO - Sending 15 to group 201. PIDs of all processes in the group: [201]
[2024-12-16T16:42:48.135+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 201
[2024-12-16T16:42:48.136+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-16T16:42:48.140+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-16T16:42:48.148+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=201, status='terminated', exitcode=2, started='16:42:47') (201) terminated with exit code 2
[2024-12-16T16:42:48.148+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-12-16T16:42:48.166+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
